from .auth import auth_login, is_staff
from .admin_views import (
    admin_banner_create,
    admin_banner_delete,
    admin_banner_edit,
    admin_banner_list,
    admin_category_create,
    admin_category_delete,
    admin_category_edit,
    admin_category_list,
    admin_company_delete,
    admin_company_edit,
    admin_company_list,
    admin_company_toggle_active,
    admin_company_update_deadline,
    admin_dashboard_home,
    admin_product_create,
    admin_product_delete,
    admin_product_edit,
    admin_product_list,
    admin_promotion_list,
    admin_user_list,
    admin_user_toggle_role,
)
from .spa import spa_entry_view
