"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_list(name, default=None):
    values = env.list(name, default=default or [])
    return [value.strip() for value in values if value and value.strip()]


def merge_lists(*groups):
    seen = set()
    merged = []
    for group in groups:
        for item in group:
            if item not in seen:
                seen.add(item)
                merged.append(item)
    return merged


def normalize_allowed_hosts(hosts):
    normalized = []
    for host in hosts:
        value = host.strip()
        if value.startswith('*.'):
            value = f'.{value[2:]}'
        normalized.append(value)
    return normalized

# Environment variables
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

DEFAULT_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'tanla-ai.ardentsoft.uz',
]

DEFAULT_FRONTEND_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://tanla-ai-frontend.vercel.app',
]

DEFAULT_CSRF_TRUSTED_ORIGINS = [
    *DEFAULT_FRONTEND_ORIGINS,
    'https://tanla-ai.ardentsoft.uz',
    'https://api.tanla-ai.ardentsoft.uz',
    'https://*.vercel.app',
]

ALLOWED_HOSTS = normalize_allowed_hosts(
    merge_lists(DEFAULT_ALLOWED_HOSTS, env_list('ALLOWED_HOSTS'))
)

# Ngrok URL
NGROK_URL = env('NGROK_URL', default=None)

CORS_ALLOWED_ORIGINS = merge_lists(
    DEFAULT_FRONTEND_ORIGINS,
    env_list('CORS_ALLOWED_ORIGINS'),
)
CORS_ALLOWED_ORIGIN_REGEXES = [r'^https://.*\.vercel\.app$']

CSRF_TRUSTED_ORIGINS = merge_lists(
    DEFAULT_CSRF_TRUSTED_ORIGINS,
    env_list('CSRF_TRUSTED_ORIGINS'),
)
if NGROK_URL:
    ALLOWED_HOSTS = normalize_allowed_hosts(
        merge_lists(ALLOWED_HOSTS, [NGROK_URL.replace('https://', '').replace('http://', '')])
    )
    CORS_ALLOWED_ORIGINS = merge_lists(CORS_ALLOWED_ORIGINS, [NGROK_URL])
    CSRF_TRUSTED_ORIGINS.append(NGROK_URL)

X_FRAME_OPTIONS = 'ALLOWALL'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_USE_SESSIONS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.tg_user_processor',
                'shop.context_processors.base_template_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication and Session Security
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'admin_dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Cookie settings for Telegram WebApp
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

# Telegram Bot
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN')

# AI Settings
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
YOLO_DOOR_MODEL_PATH = env('YOLO_DOOR_MODEL_PATH', default='')
AI_AUTO_PROCESS_CATEGORIES = ["Eshiklar", "eshiklar", "Eshik", "eshik", "Doors", "doors"]
GOOGLE_APPLICATION_CREDENTIALS = os.path.join(BASE_DIR, env('GOOGLE_APPLICATION_CREDENTIALS', default='google-cloud-key.json'))
VERTEX_AI_PROJECT = env('VERTEX_AI_PROJECT', default='project-b79a8b66-7b7a-4251-b56')
VERTEX_AI_LOCATION = env('VERTEX_AI_LOCATION', default='us-central1')
GEMINI_IMAGE_MODEL = env('GEMINI_IMAGE_MODEL', default='gemini-3.1-flash-image-preview')
GEMINI_IMAGE_FALLBACK_MODEL = env('GEMINI_IMAGE_FALLBACK_MODEL', default='gemini-2.5-flash-image')

# Admin deploy actions
ALLOW_ADMIN_DEPLOY_ACTIONS = env.bool('ALLOW_ADMIN_DEPLOY_ACTIONS', default=False)
ADMIN_RESTART_COMMAND = env('ADMIN_RESTART_COMMAND', default='sudo systemctl restart tanla-ai.service')
ADMIN_STATUS_COMMAND = env('ADMIN_STATUS_COMMAND', default='sudo systemctl status tanla-ai.service --no-pager')

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-telegram-init-data",
]

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
