# Generated by Django 5.1.5 on 2026-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image_url_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
