# Generated by Django 5.1.5 on 2026-03-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_length_product_width_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_products', to='shop.telegramuser'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('USTA', 'Usta')], default='USER', max_length=10),
        ),
    ]
