# Generated by Django 5.1.5 on 2026-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_owner_telegramuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('COMPANY', 'Company')], default='USER', max_length=10),
        ),
    ]
