# Generated by Django 5.1.5 on 2026-03-31 14:36

from django.db import migrations


def migrate_usta_to_company(apps, schema_editor):
    TelegramUser = apps.get_model('shop', 'TelegramUser')
    TelegramUser.objects.filter(role='USTA').update(role='COMPANY')

def reverse_company_to_usta(apps, schema_editor):
    TelegramUser = apps.get_model('shop', 'TelegramUser')
    TelegramUser.objects.filter(role='COMPANY').update(role='USTA')

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_telegramuser_role'),
    ]

    operations = [
        migrations.RunPython(migrate_usta_to_company, reverse_company_to_usta),
    ]
