# Generated by Django 5.1.5 on 2026-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_discount_price_product_is_on_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/raw/'),
        ),
    ]
