# Generated by Django 5.1.5 on 2026-04-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_ai_status_product_original_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_visualizations', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='shop.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
