# Generated by Django 5.1.5 on 2026-04-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_airesult'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in m² (S)', max_digits=10, null=True),
        ),
    ]
