# Generated by Django 5.1.5 on 2026-04-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='area',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for 1 m² (сум/м²)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
