# Generated by Django 5.1.5 on 2026-04-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_length_product_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
