# Generated by Django 5.1.5 on 2026-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_no_bg',
            field=models.ImageField(blank=True, null=True, upload_to='products/transparent/'),
        ),
    ]
