# Generated by Django 6.0.4 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_airesult_input_image_airesult_status_leadrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
