# Generated by Django 6.0.3 on 2026-04-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
