# Generated by Django 4.2.30 on 2026-04-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_ai_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='price_info',
            field=models.CharField(blank=True, help_text='Calculated price or dimensions info', max_length=100),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Yangi'), ('contacted', "📞 Bog'lanildi"), ('active', '⚡️ Jarayonda'), ('converted', '✅ Sotildi'), ('rejected', '❌ Rad etildi'), ('closed', '🔒 Yakunlandi')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('COMPANY', 'Company'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
