# Generated by Django 4.2.30 on 2026-04-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_leadrequest_price_info_leadrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='ai_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_leads', to='shop.airesult'),
        ),
        migrations.AlterField(
            model_name='leadrequest',
            name='lead_type',
            field=models.CharField(choices=[('call', 'Call Request'), ('telegram', 'Telegram Message'), ('measurement', 'Measurement Request'), ('visualize', 'AI Visualization')], max_length=20),
        ),
    ]
