# Generated by Django 4.2.30 on 2026-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_add_visualize_lead_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='TanlaAI', max_length=100)),
                ('default_language', models.CharField(default='uz', max_length=10)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=50)),
                ('currency', models.CharField(default='UZS', max_length=20)),
                ('ai_provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('hybrid', 'Hybrid')], default='gemini', max_length=50)),
                ('max_results_per_user', models.IntegerField(default=20)),
                ('image_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20)),
                ('enable_bg_removal', models.BooleanField(default=True)),
                ('bg_removal_mode', models.CharField(choices=[('ai', 'AI-based'), ('color', 'Color-based'), ('hybrid', 'Hybrid')], default='ai', max_length=50)),
                ('max_image_size', models.IntegerField(default=2048, help_text='Pixels')),
                ('auto_resize', models.BooleanField(default=True)),
                ('keep_aspect_ratio', models.BooleanField(default=True)),
                ('default_door_height_ratio', models.FloatField(default=0.65, help_text='0.0 to 1.0')),
                ('placement_mode', models.CharField(choices=[('center', 'Center'), ('auto', 'Auto-detect'), ('manual', 'Manual')], default='auto', max_length=50)),
                ('allow_window_placement', models.BooleanField(default=False)),
                ('snap_to_wall', models.BooleanField(default=True)),
                ('auto_create_lead', models.BooleanField(default=True)),
                ('notify_admin', models.BooleanField(default=True)),
                ('default_lead_status', models.CharField(default='new', max_length=50)),
                ('items_per_page', models.IntegerField(default=20)),
                ('enable_infinite_scroll', models.BooleanField(default=True)),
                ('show_debug_logs', models.BooleanField(default=False)),
                ('enable_deploy_actions', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
