# Generated by Django 4.2.30 on 2026-04-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_systemsettings_delete_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='ai_tests/rooms/')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='ai_tests/results/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tests', to='shop.product')),
            ],
            options={
                'verbose_name': 'AI Test',
                'verbose_name_plural': 'AI Tests',
                'ordering': ['-created_at'],
            },
        ),
    ]
