# Generated by Django 4.2.30 on 2026-04-16 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_update_ai_provider_gemini_direct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='shared_designs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'verbose_name': 'Shared Design',
                'verbose_name_plural': 'Shared Designs',
                'ordering': ['-created_at'],
            },
        ),
    ]
