# Generated by Django 4.2.30 on 2026-04-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_shareddesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='shared_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
