# Generated by Django 4.2.30 on 2026-04-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_leadrequest_shared_id_leadrequest_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shareddesign',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='shared_designs/originals/'),
        ),
    ]
