# Generated by Django 4.2.30 on 2026-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_leadrequest_is_paid_shareddesign_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
