# Generated by Django 6.0.3 on 2026-04-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_subscriptionplan_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='telegram_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aitest',
            name='telegram_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_storage_channel_id',
            field=models.CharField(blank=True, default='', help_text='Telegram kanal yoki guruh ID si (Masalan: -100123456789) AI rasmlarni saqlash uchun.', max_length=255),
        ),
        migrations.AlterField(
            model_name='airesult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_results/'),
        ),
        migrations.AlterField(
            model_name='aitest',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_tests/rooms/'),
        ),
    ]
