# Generated by Django 4.2.30 on 2026-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_airesult_telegram_file_id_aitest_telegram_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembilling',
            name='lead_price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bitta lead nomi (kelajak uchun)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_delete_results_hours',
            field=models.IntegerField(default=24, help_text="AI natijalarini necha soatdan keyin o'chirish"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_followup_minutes',
            field=models.IntegerField(default=10, help_text="Lead tushgandan keyin necha daqiqa o'tib followup qilish"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='platform_logo',
            field=models.CharField(blank=True, default='', help_text='Logo URL or Base64', max_length=500),
        ),
    ]
