# Generated by Django 4.2.30 on 2026-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_systembilling_lead_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('waiting_confirmation', 'Tasdiqlash kutilmoqda'), ('active', 'Faol'), ('expired', "Muddati o'tgan")], default='pending_payment', help_text='Kompaniya hayot davrasi holati', max_length=25),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='card_holder',
            field=models.CharField(blank=True, default='', help_text='Karta egasi ismi', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='card_number',
            field=models.CharField(blank=True, default='', help_text="To'lov uchun karta raqami", max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='monthly_price',
            field=models.IntegerField(default=100000, help_text='Oylik obuna narxi (UZS)'),
        ),
    ]
