# Generated by Django 6.0.3 on 2026-04-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_systembilling_lead_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'In Review (Paid)'), ('active', 'Active'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
