# Generated by Django 4.2.30 on 2026-04-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_company_status_systemsettings_card_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('waiting_confirmation', 'Tasdiqlash kutilmoqda'), ('active', 'Faol'), ('expired', "Muddati o'tgan"), ('rejected', 'Rad etilgan')], default='pending_payment', help_text='Kompaniya hayot davrasi holati', max_length=25),
        ),
    ]
