# Generated by Django 4.2.30 on 2026-04-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
