# Generated by Django 6.0.3 on 2026-04-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='VIP partners ignore subscription deadlines.'),
        ),
    ]
