# Generated by Django 6.0.3 on 2026-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_company_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembilling',
            name='card_holder',
            field=models.CharField(blank=True, default='', help_text='Karta egasi', max_length=100),
        ),
        migrations.AddField(
            model_name='systembilling',
            name='card_number',
            field=models.CharField(blank=True, default='', help_text="To'lov uchun karta raqami", max_length=32),
        ),
        migrations.AddField(
            model_name='systembilling',
            name='monthly_price',
            field=models.IntegerField(default=100000, help_text="Oylik obuna narxi (so'm)"),
        ),
        migrations.AddField(
            model_name='systembilling',
            name='require_manual_approval',
            field=models.BooleanField(default=True, help_text="To'lovdan keyin admin tasdiqlashi shartmi?"),
        ),
        migrations.AddField(
            model_name='systembilling',
            name='subscription_days',
            field=models.IntegerField(default=30, help_text='Obuna muddati (kun)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending_payment', "Pending (To'lov kutilmoqda)"), ('waiting_confirmation', 'Waiting (Tasdiqlash kutilmoqda)'), ('active', 'Active (Faol)'), ('expired', 'Expired (Muddati tugagan)'), ('blocked', 'Blocked (Bloklangan)')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='platform_name',
            field=models.CharField(default='Tanla AI', max_length=255),
        ),
    ]
