# Generated by Django 6.0.3 on 2026-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_systembilling_card_holder_systembilling_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription (Obuna)'), ('lead', 'Lead (Lid)'), ('other', 'Other (Boshqa)')], default='subscription', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved (Paid)'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
