# Generated by Django 6.0.4 on 2026-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_payment_payment_type_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial (Bepul sinov)'), ('pending_payment', "Pending (To'lov kutilmoqda)"), ('waiting_confirmation', 'Waiting (Tasdiqlash kutilmoqda)'), ('active', 'Active (Faol)'), ('expired', 'Expired (Muddati tugagan)'), ('blocked', 'Blocked (Bloklangan)')], default='trial', max_length=20),
        ),
    ]
