# Generated by Django 6.0.3 on 2026-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_company_ai_generation_limit_company_product_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='progress_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airesult',
            name='status_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='airesult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
