# Generated by Django 6.0.3 on 2026-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_airesult_progress_step_airesult_status_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='placement_mode',
            field=models.CharField(blank=True, default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airesult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='done', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial (Bepul sinov)'), ('pending_payment', "Pending (To'lov kutilmoqda)"), ('waiting_confirmation', 'Waiting (Tasdiqlash kutilmoqda)'), ('active', 'Active (Faol)'), ('expired', 'Expired (Muddati tugagan)'), ('blocked', 'Blocked (Bloklangan)')], default='trial', max_length=20),
        ),
    ]
