# Generated by Django 6.0.3 on 2026-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_sync_model_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_crown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_frame',
            field=models.BooleanField(default=False),
        ),
    ]
